name: Compile MihanRP

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Download MihanRP
        uses: actions/checkout@v4

      - name: Compile new.pwn
        id: compiler
        uses: knryuu/pawn-compiler-action@v1
        with:
          input: gamemodes/new.pwn
          output: gamemodes/new.amx
          includes: pawno/include

      - name: Upload new.amx
        uses: actions/upload-artifact@v4
        with:
          name: NAVARA-new-amx
          path: gamemodes/new.amx
